name: Run Dagger and Upload Output

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Dagger
        uses: dagger/dagger-for-github@v6
        with:
          version: "latest"
          verb: call
          args: all export --path ./
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print results
        run: |
          if [ -d "./outputs" ]; then
            for dir in $(ls ./outputs); do
              echo "Directory: $dir"
              for file in $(ls ./outputs/$dir); do
                echo "  File: $file"
                cat "./outputs/$dir/$file"
              done
            done
          else
            echo "No output directory found."
          fi